/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tianxunnet_fmt_Fmt */

#ifndef _Included_com_tianxunnet_fmt_Fmt
#define _Included_com_tianxunnet_fmt_Fmt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newObjectFmt
 * Signature: ()Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newObjectFmt
  (JNIEnv *, jclass);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newArrayFmt
 * Signature: ()Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newArrayFmt
  (JNIEnv *, jclass);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newByteFmt
 * Signature: (B)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newByteFmt
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newShortFmt
 * Signature: (S)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newShortFmt
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newIntFmt
 * Signature: (I)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newIntFmt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newLongFmt
 * Signature: (J)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newLongFmt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newFloatFmt
 * Signature: (F)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newFloatFmt
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newDoubleFmt
 * Signature: (D)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newDoubleFmt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newDatetimeFmt
 * Signature: (J)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newDatetimeFmt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    newBinaryFmt
 * Signature: ([B)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_newBinaryFmt
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    addField
 * Signature: (Ljava/lang/String;Lcom/tianxunnet/fmt/Fmt;)V
 */
JNIEXPORT void JNICALL Java_com_tianxunnet_fmt_Fmt_addField
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    delField
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tianxunnet_fmt_Fmt_delField
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getField
 * Signature: (Ljava/lang/String;)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_getField
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getFieldCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tianxunnet_fmt_Fmt_getFieldCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    arrayLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tianxunnet_fmt_Fmt_arrayLength
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    arrayAppend
 * Signature: (Lcom/tianxunnet/fmt/Fmt;)V
 */
JNIEXPORT void JNICALL Java_com_tianxunnet_fmt_Fmt_arrayAppend
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    arrayRemove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tianxunnet_fmt_Fmt_arrayRemove
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    arrayAt
 * Signature: (I)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_arrayAt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    incRef
 * Signature: ()Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_incRef
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    decRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tianxunnet_fmt_Fmt_decRef
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tianxunnet_fmt_Fmt_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_tianxunnet_fmt_Fmt_getByte
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_tianxunnet_fmt_Fmt_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tianxunnet_fmt_Fmt_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tianxunnet_fmt_Fmt_getLong
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_tianxunnet_fmt_Fmt_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_tianxunnet_fmt_Fmt_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getDatetime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tianxunnet_fmt_Fmt_getDatetime
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getBinary
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tianxunnet_fmt_Fmt_getBinary
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    getBinaryLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tianxunnet_fmt_Fmt_getBinaryLength
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    packet
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tianxunnet_fmt_Fmt_packet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    serverPacket
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tianxunnet_fmt_Fmt_serverPacket
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    quickSerialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tianxunnet_fmt_Fmt_quickSerialize
  (JNIEnv *, jobject);

/*
 * Class:     com_tianxunnet_fmt_Fmt
 * Method:    quickParse
 * Signature: ([B)Lcom/tianxunnet/fmt/Fmt;
 */
JNIEXPORT jobject JNICALL Java_com_tianxunnet_fmt_Fmt_quickParse
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
